# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApialertsCli < Formula
  desc "API Alerts CLI — send events from your terminal"
  homepage "https://apialerts.com"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/apialerts/apialerts-cli/releases/download/v0.0.1/apialerts-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "4cb45c186693163b72a6a14cc0998c1bda94e2253ac69a4af810c1310f54e81a"

      define_method(:install) do
        bin.install "apialerts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/apialerts/apialerts-cli/releases/download/v0.0.1/apialerts-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "2854a097902d36d0bbedcac79c8e1b0e4ebe4af5d7787f1517b44224404a1082"

      define_method(:install) do
        bin.install "apialerts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/apialerts/apialerts-cli/releases/download/v0.0.1/apialerts-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "7f77a79b3d9a51cdb103a7aa3f94f563f91c85a2d57351b47007f42c9d44e845"
      define_method(:install) do
        bin.install "apialerts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apialerts/apialerts-cli/releases/download/v0.0.1/apialerts-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "bd725199f84e32dac6f2063f6b2481a4caa25a8aa1790f91291ffe965ae883d9"
      define_method(:install) do
        bin.install "apialerts"
      end
    end
  end
end
