# This file was generated by GoReleaser. DO NOT EDIT.
cask "apialerts" do
  name "apialerts"
  desc "API Alerts CLI — send events from your terminal"
  homepage "https://apialerts.com"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apialerts"

  on_macos do
    on_intel do
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "a21b6e096d2d1a90ac7966c868691360ab05e9adfbcb0106230fdbeac30a2f43"
    end
    on_arm do
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "6d1d5bdabad369c07cd7f2897ca0b06665975be5d9a8c278629f3c02e17ffd99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "0effb2f4f161eada4b4cca5f23a95d027b88401c0fc374d450d67115c548ee43"
    end
    on_arm do
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "87e20773a57714629243c45f3009f36152b7077be5c63cf0d2efddad021248e7"
    end
  end

  # No zap stanza required
end
