# This file was generated by GoReleaser. DO NOT EDIT.
cask "apialerts-cli" do
  name "apialerts-cli"
  desc "API Alerts CLI — send events from your terminal"
  homepage "https://apialerts.com"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apialerts-cli"

  on_macos do
    on_intel do
      url "https://github.com/apialerts/apialerts-cli/releases/download/v#{version}/apialerts-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "64a73ea8b4656c01a002f31245222437c16d8c6d69befe3f277b21e9a74e31ee"
    end
    on_arm do
      url "https://github.com/apialerts/apialerts-cli/releases/download/v#{version}/apialerts-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "8b1ad4e81ef9fde85795f8cd6d6856f50d82aa5d826bcf3ccc7ebcf211579f18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/apialerts/apialerts-cli/releases/download/v#{version}/apialerts-cli_#{version}_linux_amd64.tar.gz"
      sha256 "028f6bc2e7ca9658a7631dab6e2475d386db51df54a9265ea4521ca5da5ce5b5"
    end
    on_arm do
      url "https://github.com/apialerts/apialerts-cli/releases/download/v#{version}/apialerts-cli_#{version}_linux_arm64.tar.gz"
      sha256 "ce82db40917db81f95da5b0fc70c259b8f12562f5e22b20b3752770d00c2bc12"
    end
  end

  # No zap stanza required
end
