# This file was generated by GoReleaser. DO NOT EDIT.
cask "apialerts" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "2b2585e13c12ec190544b130a947c8e7e960fb091e1353ea89ba76602fe8ca5f"
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b81575b9c9e5164e90ad16e072ce59522af7fe3c88ea0b1b7ae5f728dc37f21"
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53f4cbad75ede077ee1849c637397c8dee163df112eb7e3d968ca14ee0a3c8e2"
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb16930fa56aea04b7fa6da0f4fffc7f8e102bfedb9ee2020906c3589cfebc4f"
      url "https://github.com/apialerts/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apialerts"
  desc "API Alerts CLI - send events from your terminal"
  homepage "https://apialerts.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apialerts"

  # No zap stanza required

end
